Add fully responsive site
lukademinnosa/module1_project1 pull request #1
Opened 2023-06-03 15:33 UTC by lukademinnosa

Hello,

This is a work built by me on the Portfolio-setup mobile first project on microverse. I have ensured that all that is required is implemented. Please review.

Regards.

2023-06-03 15:58 UTC, franclobo reviewed
Hi @lukademinnosa,

![roja](https://github.com/lukademinnosa/module1_project1/assets/58642949/148dfebd-a9f2-4be0-986a-b68e0fb293ce)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has an incomplete README file. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo.

| Expected | Yours |
|---|---|
| ![image](https://github.com/lukademinnosa/module1_project1/assets/58642949/9d2c962b-31c4-472b-ba5b-95888a162ff1) | ![image](https://github.com/lukademinnosa/module1_project1/assets/58642949/2dea5f17-9cbf-48fb-ba94-221e83361332) |
| ![image](https://github.com/lukademinnosa/module1_project1/assets/58642949/9473200f-b756-4f76-a8af-6aa66082da44) | ![image](https://github.com/lukademinnosa/module1_project1/assets/58642949/b4f4a3f9-d393-44ec-b9de-8564306883fd) |





Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 17:45 UTC, lukademinnosa commented
I have fixed the issues pertaining to the README.md file. Thanks for the direction. Awaiting positive review.
Regards.

2023-06-03 18:54 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @lukademinnosa  👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Understand how to parse a Figma design to create a UI.
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 18:54 UTC, abdulhamiid commented on README.md
> +- [Live Demo Link](https://drive.google.com/file/d/1oBR0ZAG3KIy_gURd2DsV09GPQV8OWG5B/view?usp=drive_link)
Since you did not have a deployed version of your project, kindly consider removing the Live demo link in your readme, or simply put `Live demo is not available yet` 🛠🤗

What I got by clicking on the Live demo link 👀
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/e9b89e9c-2498-466f-b5f8-b267cb11d5f5)

2023-06-03 18:54 UTC, abdulhamiid commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Please kindly update all the links to your social media handles. 👍 Let's avoid broken links in our readme file for a professional repository. 🤗🛠

2023-06-03 18:54 UTC, abdulhamiid commented on index.html
> +      </nav>
Kindly use a `header` tag for the container of this section. 🛠

- Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

2023-06-03 18:54 UTC, abdulhamiid commented on index.html
> +        <div class="toggleNav"><i class="fa fa-bars"></i></div>
Kindly use a link (`a` tag). for the Logo
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/a057964e-7e4b-4fc0-a57d-684532c56fc0)

* This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

Your design
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/dd50d5fa-f6a3-44a9-a8e4-2f33c6ee3556)

Figma
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/668a21a0-d935-4768-82bf-a17bc967659f)

Please kindly adjust your design to ensure that our website looks exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

- The missing hamburger menu
- The color of the link `My Logo`

2023-06-03 18:54 UTC, abdulhamiid commented on index.html
> +        <h1>I&rsquo;m Francis.<br />Glad to see you!</h1>
Your design
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/81fdf43a-3e05-44a9-8cf6-679247b36c39)

Figma
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/b5912aa9-3f67-498b-8043-51b245a49792)

I would suggest that we increase the `font-weight` of the main title "I'm Francis. ... " and use the same text color according to the given design. 👍

2023-06-03 18:54 UTC, abdulhamiid commented on index.html
> +        </ul>
Kindly use a `ul` tag to group the list of icons, and `li` per icon; each icon has a link (`a` tag). 👍💯

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. 💪


Also, the icons are not displaying on the page. please, kindly fix that 🛠

Your design
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/6186782c-afd2-4608-b758-bffcf52a71e5)

Figma
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/39ba10de-82fd-4228-bda0-f54155c11496)

2023-06-03 18:54 UTC, abdulhamiid commented on index.html
> +        <p class="connect">LET’S CONNECT</p>
Your design
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/eb14f6a4-f749-4420-9e05-6d0e4ef672b7)

Figma
![image](https://github.com/lukademinnosa/module1_project1/assets/78251927/caf090fa-e3f6-4d14-ae5d-5603ee1c2291)

Kindly make the text `LET'S CONNECT` a link `a` tag and let's follow the design guidelines (e.g. font-wieght and colors) 💪

Apart from being semantically correct, the tag will let you connect to other sections of the website, using `href`. 👍

2023-06-04 15:24 UTC, lukademinnosa commented
Hello @abdulhamiid . I was able to look into the issues and solved them. Please review my work. Hope all is well now. The reason why icons were not visible is due to the font-awesome cdn lack of inclusion. I had downloaded the folder but I now run it from the cdn.
Regards.

2023-06-05 07:36 UTC, skyv26 reviewed
## Hi @lukademinnosa, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🟨 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExODE3YWRlNzM4ODU5NmVkZDg5ZmYxNWRiN2MxNjRiZjRkOThjNDhkNyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/CiUh5mGMBHXbl5MVfY/giphy-downsized-large.gif)

## Reason 🗒️ 
You have submitted a project, that is already reviewed by the previous code reviewer last week. It seems like you are repeating the week. Kindly create a new branch with new PR with all the required changes in order to get code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-05 09:46 UTC, closed without merging